grupoelcomercio.com.web/Models/BancoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace grupoelcomercio.com.web.Models
{
    public class BancoViewModel
    {
        [Required]
        public string NombreBanco { get; set; }
        public string DireccionBanco { get; set; }

    }
}

grupoelcomercio.com.web/Models/OrdenViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace grupoelcomercio.com.web.Models
{
    public class OrdenViewModel
    {
        [Required]
        public Guid BancoId { get; set; }

        
        public TipoMoneda TipoMoneda { get; set; }

        [Required]
        public decimal Monto { get; set; }

    }
}

grupoelcomercio.com.web/Models/ResultadoViewModel.cs
namespace grupoelcomercio.com.web.Models
{
    public class ResultadoViewModel
    {
        public string Mensage { get; set; }
    }
}

grupoelcomercio.com.web/Models/SucursalViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace grupoelcomercio.com.web.Models
{
    public class SucursalViewModel
    {
        [Required]
        public string NombreSucursal { get; set; }

        public string DireccionSucursal { get; set; }

        [Required]
        public Guid BancoId { get; set; }

    }
}

grupoelcomercio.com.web/Models/TipoMoneda.cs
using System.Runtime.Serialization;

namespace grupoelcomercio.com.web.Models
{
    public enum TipoMoneda
    {
        Soles,
        Dolares
    }
}

grupoelcomercio.com.web/Controllers/BancoController.cs
using grupoelcomercio.com.web.Models;
using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace grupoelcomercio.com.web.Controllers
{
    public class BancoController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registrar(BancoViewModel model)
        { 
            string message = SuccessMessage;
            if (ModelState.IsValid)
                client.PostAsJsonAsync("api/banco/RegistrarBanco", model);
            else
                message = ErrorMessage;

            return PartialView(PartialViewResult, new ResultadoViewModel() { Mensage = message });
        }
    }
}

grupoelcomercio.com.web/Controllers/BaseController.cs
using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Mvc;

namespace grupoelcomercio.com.web.Controllers
{
    public class BaseController : Controller
    {
        internal HttpClient client = new HttpClient();
        internal const string PartialViewResult = "~/Views/Common/Resultado.cshtml";
        internal const string SuccessMessage = "Se Registró Correctamente ☻";
        internal const string ErrorMessage = "Ocurrió un Error :'(";
        public BaseController()
        {
            client.BaseAddress = new Uri("http://localhost:21753");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }


    }
}

grupoelcomercio.com.web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace grupoelcomercio.com.web.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

    }
}

grupoelcomercio.com.web/Controllers/OrdenController.cs
using grupoelcomercio.com.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace grupoelcomercio.com.web.Controllers
{
    public class OrdenController : BaseController
    {
        

        public ActionResult Index()
        {
            ViewBag.TipoMonedas = from c in Enum.GetValues(typeof(TipoMoneda)).Cast<TipoMoneda>()
                                  select new { Id = (int)c, Value = c };

            var response = client.GetAsync("api/banco/ObtenerBancos").Result;
            if (response.IsSuccessStatusCode)
                ViewBag.Bancos = response.Content.ReadAsAsync<List<object>>().Result;




            return View();
        }

        [HttpPost]
        public ActionResult Registrar(OrdenViewModel model)
        {
            Task<HttpResponseMessage> response = null;
            string message = SuccessMessage;
            if (ModelState.IsValid)
                response = client.PostAsJsonAsync("api/orden/PagarOrden", model);
            else
                message = ErrorMessage;

            return PartialView(PartialViewResult, new ResultadoViewModel() { Mensage = message });
        }
    }
}

grupoelcomercio.com.web/Controllers/SucursalController.cs
using grupoelcomercio.com.web.Models;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Mvc;

namespace grupoelcomercio.com.web.Controllers
{
    public class SucursalController : BaseController
    {

        public ActionResult Index()
        {
            SucursalViewModel model = new SucursalViewModel();
            var response = client.GetAsync("api/banco/ObtenerBancos").Result;
            if (response.IsSuccessStatusCode)
                ViewBag.Bancos = response.Content.ReadAsAsync<List<object>>().Result;
            

            return View();
        }

        [HttpPost]
        public ActionResult Registrar(SucursalViewModel model)
        {
            
            string message = "";
            if (ModelState.IsValid)
            {
                message = SuccessMessage;
                client.PostAsJsonAsync("api/sucursal/RegistrarSucursal", model);
            }
            else
            {
                message = ErrorMessage;
            }


            return PartialView(PartialViewResult, new ResultadoViewModel() { Mensage = message });
        }

        
    }
}

grupoelcomercio.com.web/Views/Banco/Index.cshtml
@model grupoelcomercio.com.web.Models.BancoViewModel
@{
    ViewBag.Title = "Registro de Bancos";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Registro de Banco</h2>
@using (Ajax.BeginForm("Registrar", "Banco", null, new AjaxOptions() {
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "resultTarget" }, new { @id = "registro-banco" }))
{

    <div class="form-group">
      
        @Html.LabelFor(x => x.NombreBanco)
        @Html.TextBoxFor(x => x.NombreBanco, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.NombreBanco, "Debe ingresar un nombre", new { @class = "has-error" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.DireccionBanco)
        @Html.TextAreaFor(x => x.DireccionBanco, new { @class = "form-control" })
    </div>

    <input type="submit" class="btn btn-default" value="Registrar" />

}

<div id="resultTarget"></div>

grupoelcomercio.com.web/Views/Common/Resultado.cshtml
@model grupoelcomercio.com.web.Models.ResultadoViewModel

<div class="panel panel-default" >
    @Html.DisplayFor(x => x.Mensage)
</div>

grupoelcomercio.com.web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Index</h2>

grupoelcomercio.com.web/Views/Orden/Index.cshtml
@model grupoelcomercio.com.web.Models.OrdenViewModel
@{
    ViewBag.Title = "Orden de Pago";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Registro de Banco</h2>
@using (Ajax.BeginForm("Registrar", "Orden", null, new AjaxOptions()
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "resultTarget"
}, new { @id = "registro-orden" }))
{

    <div class="form-group">

        @Html.LabelFor(x => x.Monto)
        @Html.TextBoxFor(x => x.Monto, new { @class = "form-control" })
        @Html.ValidationMessageFor(X => X.Monto, "Debe ingresar el monto", new { @class = "has-error" })
    </div>


    <div class="form-group">
        @Html.LabelFor(x => x.BancoId)
        @Html.DropDownListFor(x => x.BancoId, new SelectList(ViewBag.Bancos, "Id", "Nombre"), "--Seleccione--", new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.TipoMoneda)
        @Html.DropDownListFor(x => x.TipoMoneda, new SelectList(ViewBag.TipoMonedas, "Id", "Value"), "--Seleccione--", new { @class = "form-control" })
    </div>


    <input type="submit" class="btn btn-default" value="Registrar" />

}

<div id="resultTarget"></div>

grupoelcomercio.com.web/Views/Shared/Layout.cshtml
@{
    Func<string, string, string> IsActive = (controllerName, className) => 
        ViewContext.RouteData.Values["Controller"].ToString() == controllerName ? className : string.Empty;
}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/bundles/style")


</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Brand</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="@IsActive("Home", "active")"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="@IsActive("Banco", "active")"><a href="@Url.Action("Index", "Banco")">Banco</a></li>
                    <li class="@IsActive("Sucursal", "active")"><a href="@Url.Action("Index", "Sucursal")">Sucursal</a></li>
                    <li class="@IsActive("Orden", "active")"><a href="@Url.Action("Index", "Orden")">Orden de Pago</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <section id="content" class="container-fluid">
        @RenderBody()
    </section>
    @Scripts.Render("~/bundles/script")
</body>
</html>

grupoelcomercio.com.web/Views/Sucursal/Index.cshtml
@model grupoelcomercio.com.web.Models.SucursalViewModel
@{
    ViewBag.Title = "Registro de Sucursal";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Registro de Banco</h2>
@using (Ajax.BeginForm("Registrar", "Sucursal", null, new AjaxOptions()
{
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "resultTarget"
}, new { @id = "registro-sucursal" }))
{

    <div class="form-group">

        @Html.LabelFor(x => x.NombreSucursal)
        @Html.TextBoxFor(x => x.NombreSucursal, new { @class = "form-control" })
        @Html.ValidationMessageFor(X => X.NombreSucursal, "Debe ingresar un nombre", new { @class = "has-error" })
    </div>
    <div class="form-group">
        @Html.LabelFor(x => x.DireccionSucursal)
        @Html.TextAreaFor(x => x.DireccionSucursal, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.BancoId)
        @Html.DropDownListFor(x => x.BancoId,new SelectList(ViewBag.Bancos, "Id", "Nombre"), "--Seleccione--", new { @class="form-control" })
    </div>


    <input type="submit" class="btn btn-default" value="Registrar" />

}

<div id="resultTarget"></div>